CREATE USER 'carer_you'@'localhost' identified by '22042003';
GRANT ALL PRIVILEGES ON *.* TO 'carer_you'@'localhost' WITH GRANT OPTION;

CREATE DATABASE DB_CARER_YOU CHARACTER SET = 'UTF8MB4' COLLATE = 'UTF8MB4_GENERAL_CI';
USE DB_CARER_YOU;

CREATE TABLE IF NOT EXISTS TB_UF
(
	SG_UF CHAR(2) NOT NULL,
    NM_UF VARCHAR(30) NOT NULL,
    PRIMARY KEY(SG_UF)
)
ENGINE = InnoDB;

INSERT INTO TB_UF VALUES('SP','São Paulo');

CREATE TABLE IF NOT EXISTS TB_CIDADE
(
	ID_CIDADE INT NOT NULL AUTO_INCREMENT,
    SG_UF CHAR(2) NOT NULL,
    NM_CIDADE VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID_CIDADE),
    CONSTRAINT FK_CIDADE_UF
		FOREIGN KEY(SG_UF)
			REFERENCES TB_UF(SG_UF)
				ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = InnoDB;

INSERT INTO TB_CIDADE VALUES
(DEFAULT,'SP','Santos'),
(DEFAULT,'SP','São Vicente');

CREATE TABLE IF NOT EXISTS TB_GENERO_USUARIO
(
	ID_GENERO_USUARIO INT NOT NULL AUTO_INCREMENT,
    DS_GENERO_USUARIO VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID_GENERO_USUARIO),
    CONSTRAINT UNIQUE_GENERO_USUARIO
		UNIQUE KEY(DS_GENERO_USUARIO)
)
ENGINE = InnoDB;

INSERT INTO TB_GENERO_USUARIO VALUES
(DEFAULT,'Masculino'),
(DEFAULT, 'Feminino'),
(DEFAULT, 'Prefiro Não informar');

CREATE TABLE IF NOT EXISTS TB_STATUS_USUARIO
(
	ID_STATUS_USUARIO INT NOT NULL AUTO_INCREMENT,
    DS_STATUS_USUARIO VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID_STATUS_USUARIO),
    CONSTRAINT UNIQUE_STATUS_USUARIO
		UNIQUE KEY(DS_STATUS_USUARIO)
)
ENGINE = InnoDB;
INSERT INTO TB_STATUS_USUARIO VALUES
(DEFAULT,'Disponível'),
(DEFAULT,'Indisponível');

INSERT INTO TB_STATUS_USUARIO VALUES
(DEFAULT,'Em análise');

CREATE TABLE IF NOT EXISTS TB_TIPO_USUARIO
(
	ID_TIPO_USUARIO INT NOT NULL AUTO_INCREMENT,
    DS_TIPO_USUARIO VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID_TIPO_USUARIO),
    CONSTRAINT UNIQUE_TIPO_USUARIO
		UNIQUE KEY(DS_TIPO_USUARIO)
)
ENGINE = InnoDB;

INSERT INTO TB_TIPO_USUARIO VALUES
(DEFAULT,'Cliente'),
(DEFAULT,'Profissional'),
(DEFAULT,'Admin');

CREATE TABLE IF NOT EXISTS TB_USUARIO
(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NM_USUARIO VARCHAR(50) NOT NULL,
    DS_EMAIL VARCHAR(100) NOT NULL,
    DS_SENHA VARCHAR(260) NOT NULL,
    DS_RG VARCHAR(12) NOT NULL,
    NM_FOTO_PERFIL VARCHAR(100) NOT NULL,
    ID_TIPO_USUARIO INT,
    ID_STATUS_USUARIO INT DEFAULT 1,
    ID_GENERO_USUARIO INT,
    ID_CIDADE_USUARIO INT,
    PRIMARY KEY(ID_USUARIO),
    CONSTRAINT FK_USUARIO_TIPO_USUARIO
		FOREIGN KEY(ID_TIPO_USUARIO)
			REFERENCES TB_TIPO_USUARIO(ID_TIPO_USUARIO)
				ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_USUARIO_STATUS_USUARIO
		FOREIGN KEY(ID_STATUS_USUARIO)
			REFERENCES TB_STATUS_USUARIO(ID_STATUS_USUARIO)
				ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_USUARIO_GENERO_USUARIO
		FOREIGN KEY(ID_GENERO_USUARIO)
			REFERENCES TB_GENERO_USUARIO(ID_GENERO_USUARIO)
				ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT FK_USUARIO_CIDADE
		FOREIGN KEY(ID_CIDADE_USUARIO)
			REFERENCES TB_CIDADE(ID_CIDADE)
				ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT UNIQUE_EMAIL
		UNIQUE KEY(DS_EMAIL)
)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS TB_USUARIO_PROFISSIONAL
(
	ID_USUARIO_PROFISSIONAL INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT,
    NM_ARQUIVO_CERTIFICADO VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_USUARIO_PROFISSIONAL),
    CONSTRAINT FK_USUARIO_PROFISSIONAL_USUARIO
		FOREIGN KEY(ID_USUARIO)
			REFERENCES TB_USUARIO(ID_USUARIO)
				ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT UNIQUE_ID_USUARIO
		UNIQUE KEY(ID_USUARIO)
)
ENGINE = InnoDB;

DELIMITER //

CREATE PROCEDURE CADASTRAR_USUARIO(nome varchar(50), email varchar(100), senha varchar(260), rg varchar(12), foto_perfil varchar(100), tipo_usuario varchar(30), genero_usuario varchar(30), nome_cidade varchar(50), nome_certificado varchar(100))
BEGIN
	IF tipo_usuario = "Cliente" OR tipo_usuario = "Admin" THEN
		INSERT INTO TB_USUARIO VALUES
        (DEFAULT, nome, email, senha, rg, foto_perfil, (SELECT ID_TIPO_USUARIO FROM TB_TIPO_USUARIO WHERE DS_TIPO_USUARIO = tipo_usuario), DEFAULT, (SELECT ID_GENERO_USUARIO FROM TB_GENERO_USUARIO WHERE DS_GENERO_USUARIO = genero_usuario), (SELECT ID_CIDADE FROM TB_CIDADE WHERE NM_CIDADE = nome_cidade));
	ELSE
		INSERT INTO TB_USUARIO VALUES
		(DEFAULT, nome, email, senha, rg, foto_perfil, (SELECT ID_TIPO_USUARIO FROM TB_TIPO_USUARIO WHERE DS_TIPO_USUARIO = tipo_usuario), 3, (SELECT ID_GENERO_USUARIO FROM TB_GENERO_USUARIO WHERE DS_GENERO_USUARIO = genero_usuario), (SELECT ID_CIDADE FROM TB_CIDADE WHERE NM_CIDADE = nome_cidade));
        INSERT INTO TB_USUARIO_PROFISSIONAL VALUES
        (DEFAULT, (SELECT ID_USUARIO FROM TB_USUARIO WHERE DS_EMAIL = email), nome_certificado);
    END IF;
END //
DELIMITER ;

DELIMITER //

CREATE PROCEDURE LOGIN_USUARIO (email varchar(100), senha varchar(260))
BEGIN
	SELECT US.ID_USUARIO, TP.DS_TIPO_USUARIO FROM TB_USUARIO AS US INNER JOIN TB_TIPO_USUARIO AS TP ON (US.ID_TIPO_USUARIO = TP.ID_TIPO_USUARIO) WHERE US.DS_EMAIL = email AND DS_SENHA = senha;
END //
DELIMITER ;

DROP procedure LOGIN_USUARIO;
DROP PROCEDURE CADASTRAR_USUARIO;

select * from tb_usuario;

select * from tb_usuario_profissional;

delete from tb_usuario where id_usuario > 0;
delete from tb_usuario_profissional where id_usuario_profissional  > 0;
